#pragma once

namespace Global {
#define NAMESIZE 32
#define STRUCTNAMESIZE 64
#define ADDRESSSIZE 16
#define VALUESIZE 256
#define TYPESIZE 64
#define INSTRUCTIONSIZE 512
#define OUTPUTSIZE 1024
#define NUMBEROFPRINTARGUMENTS 32
#define STRUCTMEMBERS 512
#define LOOPMAX 128
#define MAXINCLUDEDFILES 128
#define PATHSIZE 256
}